version: "3.9"

services:
  api:
    image: einkaufs_api/api
    build: .
    volumes:
      - .:/app
    expose:
      - 80
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.2
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    env_file:
      - .env.prod.db
    ports:
      - "5434:5432"
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - api
    restart: always
