version: "3.9"

services:
  api:
    image: einkaufs_api/api
    build: .
    volumes:
      - .:/app
    ports:
      - "8003:80"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.2
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always