version: "3.9"

services:
  api:
    image: einkaufs_api/api
    build: .
    volumes:
      - .:/app
    ports:
      - "8003:80"
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.2
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_NAME=einkaufs_api
      - POSTGRES_USER=einkaufs_api
      - POSTGRES_PASSWORD=51caf0676111
    ports:
      - "5434:5432"
    restart: always
