# Generated by Django 4.2.15 on 2024-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteditem',
            name='item_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collecteditem',
            name='name',
            field=models.TextField(),
        ),
    ]
