# Generated by Django 4.2.15 on 2024-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_alter_collecteditem_item_id_alter_collecteditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteditem',
            name='user_agent',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
