# Generated by Django 4.2.15 on 2024-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_collecteditem_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteditem',
            name='user_key',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
